kind: pipeline
type: kubernetes
name: Test

trigger:
  branch:
    - main
  event:
    include:
      - pull_request

steps:
- name: Test application 
  image: mcr.microsoft.com/dotnet/sdk:6.0-focal
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
    TCDN_VAULT_TOKEN:
      from_secret: VAULT_DEV_TOKEN
    TCDN_VAULT_ENDPOINT:
      from_secret: VAULT_DEV_ENDPOINT

  commands:
    - dotnet build -c Release
    - dotnet test -c Release



- name: discord-pr
  pull: always
  image: appleboy/drone-discord
  settings:
    avatar_url: https://www.pngitem.com/pimgs/m/86-868269_drone-logo-png-transparent-drone-ci-logo-png.png
    message: "{{#success build.status}} ✅ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` succeeded.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{else}} ❌ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` failed.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{/success}}"
    webhook_id:
      from_secret: DISCORD_WEBHOOK_PR_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_PR_TOKEN
  when:
    status: [success, failure]
---
kind: pipeline
type: kubernetes
name: Dev

trigger:
  branch:
    - main
  event:
    include:
      - push

steps:

- name: Build docker image & push to repository
  image: plugins/docker
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_PASSWORD
    VAULT_TOKEN:
      from_secret: VAULT_DEV_TOKEN
  settings:
    registry: ghcr.io
    repo: ghcr.io/tipcat-net/tipcat-net-payout
    tags:
      - ${DRONE_COMMIT_SHA:0:7}-DEV
      - ${DRONE_COMMIT_BRANCH}
      
    force_tag: true
    use_cache: true
    username:
      from_secret: GITHUB_LOGIN
    password:
      from_secret: GITHUB_PASSWORD
    build_args_from_env:
      - GITHUB_TOKEN
      - VAULT_TOKEN

- name: Deploy
  image: pelotech/drone-helm3
  settings:
    mode: upgrade
    chart: ./Helm
    release: payout
    values_files: ["Helm/values_dev.yaml"]
    namespace: dev
    skip_tls_verify: true
    wait_for_upgrade: true
    values: image.tag=${DRONE_COMMIT_SHA:0:7}-DEV
  environment:
    KUBE_API_SERVER:
      from_secret: KUBERNETES_DEV_API
    KUBE_TOKEN:
      from_secret: KUBERNETES_DEV_TOKEN
    
- name: discord
  pull: always
  image: appleboy/drone-discord
  settings:
    avatar_url: https://www.pngitem.com/pimgs/m/86-868269_drone-logo-png-transparent-drone-ci-logo-png.png
    message: "{{#success build.status}} ✅ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` on dev succeeded.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{else}} ❌ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` on production failed.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{/success}}"
    webhook_id:
      from_secret: DISCORD_WEBHOOK_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_TOKEN
  when:
    status: [success, failure]
