namespace: dev
cronjobs:
  crone-8am:  
    schedule: "0 5 * * *"
  crone-15pm:
    schedule: "0 12 * * *"


restartPolicy: Never
image:
  repository: ghcr.io/tipcat-net/tipcat-net-payout
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets:
               - name: key-github

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
     cpu: 200m
     memory: 512Mi    
     
env:
  ASPNETCORE_URLS: http://*:80
  ASPNETCORE_ENVIRONMENT: "Development"
  TCDN_CONSUL_HTTP_ADDR: "https://consul.tipcat.net/"
  TCDN_CONSUL_HTTP_TOKEN: f44ea20c-6aac-61a5-61b7-47df6891d173


